server:
    port: 8183
spring:
    application:
        name: user-service
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost/micro
        username: rintu
        password: Open@120
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            # minIdle: 10
            idle-timeout: 10000
            maximum-pool-size: 30
eureka:
    client:
        registerWithEureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8661/eureka
    instance:
        hostname: localhost